### ISSUE TITLE
Client & Server application breaking

### ISSUE THREAD

**Issue by samarpanda** [ucemrecan/youtube-video-downloader#5]
# Client & server application breaking

1. One of the npm package missing in client
2. Updated `ytdl-core` package needs to be used else it is downloading empty video

## Required Fixes:

1. client devDependency package missing i.e `cd client; npm i live-server -D;`
2. server `ytld-core` updated package needs to be used as the old one seems to be failing with empty file. Update package can be installed using `cd server; npm i @distube/ytdl-core;`

**Comment by ucemrecan** [comment]
Thanks for your attention and contribution, @samarpanda . I've updated the package to @distube/ytdl-core.
